# Generated by Django 2.1.1 on 2018-10-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corner', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
