# Generated by Django 2.1.1 on 2018-10-04 12:56

from django.db import migrations


def add_products(apps, schema_editor):
    import random
    products = []
    product_markers = apps.get_model('products', 'ProductMarker').objects.all()
    categories = apps.get_model('products', 'Category').objects.all()
    images = apps.get_model('products', 'Image').objects.all()

    for i in range(1, 100):
        products.append(
            {
                'name': 'Product_' + str(i),
                'short_text': 'Product short text',
                'long_text': 'Product long text',
                'now_price': random.randint(1000, 1500),
                'old_price': random.randint(1500, 2000),
                'product_marker': random.choice(product_markers),
                'category': random.choice(categories),
                'image': random.choice(images)
            }
        )

    product = apps.get_model('products', 'Product')
    for prod in products:
        product.objects.create(
            name=prod['name'],
            short_text=prod['short_text'],
            long_text=prod['long_text'],
            now_price=prod['now_price'],
            old_price=prod['old_price'],
            product_marker=prod['product_marker'],
            category=prod['category'],
            image=prod['image']
        )


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0004_product'),
    ]

    operations = [
        migrations.RunPython(
            add_products,
            lambda x, y: (x, y)
        )
    ]
