# Generated by Django 2.1.1 on 2018-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=150)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=models.SET('deleted'), to='main.Author')),
            ],
        ),
    ]
