# Generated by Django 2.1.1 on 2018-10-03 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mainpagecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Author'),
        ),
    ]
