# Generated by Django 2.1.1 on 2018-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181003_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpagecontent',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
